### PR TITLE
Set focus by default and allow sliding with arrow-keys

### PR DESCRIPTION
**Pull request by liorbentov**

### CODE REVIEW

**Comment by vvo** [comment]
@liorbentov Thanks a lot for contribution, as said in https://github.com/algolia/react-nouislider/pull/22 (whose content might be very relevant to your PR), react-nouislider aims at being a simple wrapper around nouislider library: https://refreshless.com/nouislider/.

Thus I am not looking at including any specific code directly inside react-nouislider. Because it would make the library different than the wrapped one and also raise the confusion on the goals of react-nouislider.

What you did seems awesomes though, could you first:
- describe exactly what you are adding and how the arrows keys are working
- how is this different from #22 
- see how this and #22 could be implemented inside nouislider directly, @leongersen is more than open at supporting those

Thanks!

**Comment by vvo** [comment]
This needs to be implemented in the underlying project: http://refreshless.com/nouislider/

I will add a note on the README of react-nouislider about new features.

Thanks for contributing!

**Comment by liorbentov** [comment]
Not really sure what you meant.. is it going to be in react-nouislider?
Because it is a key-feature accessibility-wise...

**Comment by vvo** [comment]
Hi @liorbentov, sorry if I was not precise enough.

The goal of react-nouislider is to provide a React like slider wrapping the original http://refreshless.com/nouislider/ code.

We do not want to add new features inside react-nouislider because that would raise more issues over time. What I advise you to do is to discuss on the https://github.com/leongersen/noUiSlider repository about adding new features to the library.

And once those new features are available in https://github.com/leongersen/noUiSlider then we can link them here in react-nouislider.

Adding new features to react-nouislider would create a difference in term of feature scope between react-nouislider and the original wrapped nouislider library.

I hope you understand that and I advise you to discuss your new feature on the original repository https://github.com/leongersen/noUiSlider.

Thanks!

**Pull request closed without merging**
