### PR TITLE
fix(componentWillReceiveProps): uses new props values

### PR DESCRIPTION
**Pull request by bobylito**
Force rerendering of noUISlider as the new props may be passed that are not rerendered by noUISlider if just set to the object

### CODE REVIEW

**Comment by vvo** [comment]
@bobylito can you explain what you are solving/why you need this PR?

**Comment by vvo** [comment]
No more needed to update the options of the slider? (When ranges are updated we need to update the slider ranges)

**Comment by vvo** [comment]
Ok got some context from instantsearch. Are we destroying and creating the slider on every update here?

**Comment by bobylito** [comment]
Yes (i know it's weird). This is the recommended way by nouislider http://refreshless.com/nouislider/more/#section-update

**Comment by vvo** [comment]
> Yes (i know it's weird). This is the recommended way by nouislider

Indeed this is still in the documentation but since that I introduced updateOptions to nouislider to be able to update the options without having to destroy/create it everytime. See https://github.com/leongersen/noUiSlider/pull/515

**Comment by bobylito** [comment]
updateOptions doesn't update the pips nor the bounds.

**Comment by vvo** [comment]
> updateOptions doesn't update the pips nor the bounds.

indeed

**Pull request closed without merging**
