### PR TITLE
Added slide event handler

### LINKED ISSUE #7: onSlide event?
I recently discovered that rerendering onUpdate will make react behave poorly, because `update` is fired immediately onload. If using `update` for rendering something, `update` will trigger a rerender, which will trigger `update`, which triggers a rerender, and yadda yadda yadda.

`on('slide')`, on the other hand, does _not_ fire on rerender—only on a slide event (obviously).

I'm willing to add this functionality to the slider if y'all are accepting pull requests :)

### PR DESCRIPTION
**Pull request by sean-clayton**
This will close #7 that I created :smiley_cat:

### CODE REVIEW

**Comment by redox** [comment]
Thank you for contributing @sean-clayton, that makes a a lot of sense!

**Comment by vvo** [comment]
Awesome! @sean-clayton can you also remove the listener on destroy in a PR? Otherwise you might leak memory it seems. Nouislider is not removing anything for us here: https://github.com/leongersen/noUiSlider/blob/befd4a23c698404494c659e8b08b43063b613490/src/js/scope.js#L155

**Comment by sean-clayton** [comment]
@vvo Sorry for chiming in late—very busy lately! But, I still want to tackle this issue. Is there any kind of steps I can do to reproduce it? I modeled `slide` after both `change` and `update`, but I didn't find anything about those being destroyed in the code. Any pointers to get me in the right direction?

**Comment by vvo** [comment]
Yes I guess it would just be a matter of using componentWillUnmount https://facebook.github.io/react/docs/component-specs.html and call this.slider.off('eventName', this.props.eventHandler).

Currently we only call destroy() but it's not sufficient, I created an issue in nouislider also: https://github.com/leongersen/noUiSlider/issues/612

So if you could do a PR where we unsubscribe from events, that would be awesome.

I agree it was not done before you added the event.. Up to you! :)

**Pull request merged**
