### PR TITLE
Support aria-* + accessibility via onKeyDown

### PR DESCRIPTION
**Pull request by vincentaudebert**

### CODE REVIEW

**Comment by vvo** [comment]
Awesome work! I don't know how much work it would take but I feel this should all be done in the original project rather than in the React wrapper.

So that the original project will also benefit from your awesome work: https://github.com/leongersen/noUiSlider

Could you do that?

**Comment by vincentaudebert** [comment]
Thanks @vvo
We just added a task to our backlog. We will do it if we have a bit of spare time :)
There's already a discussion about it https://github.com/leongersen/noUiSlider/issues/246
And leongersen doesn't sound that keen but we could just push a PR and see :)

**Comment by vincentaudebert** [comment]
Disabled all of this by default. You now need to specify tabIndex 0 to get aria support + keydown
Also changed to generic css classes that you can overwrite with new props.

**Comment by vvo** [comment]
@vincentaudebert Are you using instantsearch.js?

Given your knowledge of accessibility I believe @leongersen would be happy to hear that you were able to make nouislider accessible and that it would only require some additions to nouislider.

**Comment by vincentaudebert** [comment]
@vvo No I am not but it looks like a pretty cool project though :)

I will see if I have time to make a PR for accessibility on the main nouislider repo.
Any chance you could merge this PR meanwhile? and publish it to npm so it's available directly via npm install? :)

**Comment by vvo** [comment]
I can understand this would require some work to make it through noUislider main repo but I never planned to make react-nouislider more than a wrapper to noUislider. It would raise the maintenance level for us while introducing some surprises for the users like "This is part noUislider, part react-nouislider" => confusing.

In the meantime what I would advise you is rename your fork package.name to react-nouislider-aria and npm publish inside it.

So that you can still install it with npm install, no problem.

This is actually what we did when we submitted multiple PRs to noUislider, we have a "nouislider-algoliafork" that we would publish and use here while waiting for the merge in the main project.

I really appreciate the time you took to do that PR and the quality of the work. But I'd rather not split the projects for ease of use while it's not merged in the main nouislider. I hope you understand that.

**Comment by vincentaudebert** [comment]
all good @vvo . We thought of the npm package and we will probably end up doing this for now :)
Hopefully we have time to move it to main repo one day :)

Thanks for your reactivity and your answers :)

**Comment by pixelastic** [comment]
@vincentaudebert: Just wanted to chime in and say that I love what you do at Springload. Nice quality  blog you have :)

**Comment by vincentaudebert** [comment]
Thanks a lot @pixelastic :)

**Comment by leongersen** [comment]
Just wanted to chime in and say I'd be happy to accept a pull request adding aria support. I don't know how to (properly) test it, though.

**Pull request closed without merging**
